version: '3'
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    volumes:
      - ./seed/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379